version: '3.8'
services:
  telegram_bot:
    build: ./telegram_bot
    container_name: telegram_bot
    command: python bot.py
    ports:
      - "8000:8000"
    volumes:
      - ./telegram_bot:/app

  notion_webhook:
    build: ./server
    container_name: notion_webhook
    command: python flask.py
    ports:
      - "8001:8001"
    volumes:
      - ./notion_webhook:/app
