"""baseline: create notion_events table

Revision ID: 767b1a482928
Revises: 
Create Date: 2025-07-26 16:27:46.647545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767b1a482928'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('last_edited_time', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notion_events_created_at'), 'notion_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_notion_events_id'), 'notion_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notion_events_id'), table_name='notion_events')
    op.drop_index(op.f('ix_notion_events_created_at'), table_name='notion_events')
    op.drop_table('notion_events')
    # ### end Alembic commands ###
